# Generated by Django 5.1 on 2026-02-21 16:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cref', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objetivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adipometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triciptal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supra_iliaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axilar_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adipometria', to='core.avaliacaofisica')),
            ],
        ),
        migrations.CreateModel(
            name='Circunferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdome', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circunferencias', to='core.avaliacaofisica')),
            ],
        ),
    ]
