# Generated by Django 5.1 on 2026-02-12 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objetivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adipometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triciptal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supra_iliaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axilar_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adipometria', to='core.avaliacaofisica')),
            ],
        ),
        migrations.CreateModel(
            name='Circunferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdome', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circunferencias', to='core.avaliacaofisica')),
            ],
        ),
    ]
