# Generated by Django 6.0.2 on 2026-04-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexercicio',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='videoexercicio',
            name='video_id',
        ),
        migrations.CreateModel(
            name='VariacaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gif', models.ImageField(upload_to='exercicios/')),
                ('grupo_muscular', models.CharField(blank=True, max_length=50, null=True)),
                ('exercico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='core.videoexercicio')),
            ],
        ),
    ]
