# Generated by Django 6.0.2 on 2026-04-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_videoexercicio_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('descanso', models.IntegerField(help_text='em segundos')),
                ('carga', models.CharField(blank=True, max_length=50)),
                ('ordem', models.IntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videoexercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='core.treino')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variacaoexercicio')),
            ],
        ),
    ]
