# Generated by Django 5.1 on 2026-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260422_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='descricao',
            field=models.TextField(),
        ),
    ]
