# Generated by Django 5.1 on 2026-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_variacaoexercicio_grupo_muscular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexercicio',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='gif',
            field=models.FileField(upload_to='gifs/'),
        ),
        migrations.AlterField(
            model_name='videoexercicio',
            name='gif',
            field=models.FileField(default='', upload_to='gifs/'),
            preserve_default=False,
        ),
    ]
