# Generated by Django 5.1 on 2026-04-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260422_1640'),
    ]

    # `0001_initial` already creates `descricao` with the final definition.
    operations = []
