# Generated by Django 5.1 on 2026-04-23 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_token_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
