# Generated by Django 6.0.2 on 2026-04-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exerciciotreino_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciotreino',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='exercicios/'),
        ),
    ]
