# Generated by Django 5.1 on 2026-04-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_token_field'),
    ]

    # `0001_initial` already contains the final `token` definition.
    operations = []
