# Generated by Django 5.1 on 2026-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_treino_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='nome',
        ),
    ]
