# Generated by Django 6.0.2 on 2026-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exerciciotreino_gif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacaoexercicio',
            old_name='exercico',
            new_name='exercicio',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='gif',
        ),
        migrations.AddField(
            model_name='videoexercicio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='exercicios/imagem/'),
        ),
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='gif',
            field=models.ImageField(upload_to='exercicios/gif/'),
        ),
    ]
