# Generated by Django 5.1 on 2026-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_variacaoexercicio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='gif',
            field=models.FileField(max_length=300, upload_to='gifs/'),
        ),
    ]
