# Generated by Django 6.0.2 on 2026-04-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_exercico_variacaoexercicio_exercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
